@startuml Use_Cases_Admin
left to right direction

actor "Administrateur" as Admin

package "Back-Office (Admin)" {
  usecase "Afficher les Articles" as UC_View
  usecase "Ajouter un Article" as UC_Add
  usecase "Modifier un Article" as UC_Edit
  
}

Admin -- UC_View
Admin -- UC_Add
Admin -- UC_Edit


UC_Add .> UC_View : <<extend>>
UC_Edit .> UC_View : <<extend>>

@enduml
